# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tamashii_pb2 as tamashii__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tamashii_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TamashiiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTamashii = channel.unary_unary(
                '/tamashii.TamashiiService/CreateTamashii',
                request_serializer=tamashii__pb2.CreateTamashiiRequest.SerializeToString,
                response_deserializer=tamashii__pb2.CreateTamashiiResponse.FromString,
                _registered_method=True)
        self.GetTamashii = channel.unary_unary(
                '/tamashii.TamashiiService/GetTamashii',
                request_serializer=tamashii__pb2.GetTamashiiRequest.SerializeToString,
                response_deserializer=tamashii__pb2.GetTamashiiResponse.FromString,
                _registered_method=True)


class TamashiiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTamashii(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTamashii(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TamashiiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTamashii': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTamashii,
                    request_deserializer=tamashii__pb2.CreateTamashiiRequest.FromString,
                    response_serializer=tamashii__pb2.CreateTamashiiResponse.SerializeToString,
            ),
            'GetTamashii': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTamashii,
                    request_deserializer=tamashii__pb2.GetTamashiiRequest.FromString,
                    response_serializer=tamashii__pb2.GetTamashiiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tamashii.TamashiiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tamashii.TamashiiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TamashiiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTamashii(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tamashii.TamashiiService/CreateTamashii',
            tamashii__pb2.CreateTamashiiRequest.SerializeToString,
            tamashii__pb2.CreateTamashiiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTamashii(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tamashii.TamashiiService/GetTamashii',
            tamashii__pb2.GetTamashiiRequest.SerializeToString,
            tamashii__pb2.GetTamashiiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
